### ISSUE TITLE
how to use this Lib?

### ISSUE THREAD

**Issue by SigmaLGX** [marcusvaltonen/python-droneposelib#6]
Thank you for sharing, but how does this library work

Does it have documentation?

**Comment by marcusvaltonen** [comment]
Hello, the library is under development, and there is no documentation so far. It will be available in the future.

Right now we are incorporating the solvers in a RANSAC framework. When this is done we will improve the documentation.

To use the minimal solvers:

`import numpy as np
import droneposelib as dpl
output = dpl.get_valtonenornhag_arxiv_2021_frEfr(np.asfortranarray(x1), np.asfortranarray(x2),
                                                                                 np.asfortranarray(R1), np.asfortranarray(R2), use_fast_solver)

output = dpl.get_valtonenornhag_arxiv_2021_fEf(np.asfortranarray(x1), np.asfortranarray(x2),
                                                                                 np.asfortranarray(R1), np.asfortranarray(R2))

output = dpl.get_valtonenornhag_arxiv_2021_rEr(np.asfortranarray(x1), np.asfortranarray(x2),
                                                                                 np.asfortranarray(R1), np.asfortranarray(R2))`

where x1, x2 are the point correspondences (np.ndarray of correct size), R1, R2 np.ndarray (3x3) are the rotation matrices. For the frEfr solver you also have a boolean option for use_fast_solver -- it is faster, but not as accurate.

**Comment by SigmaLGX** [comment]
thank you
